from flask_sqlalchemy import SQLAlchemy
from datetime import datetime

db = SQLAlchemy()

class Person(db.Model):
    id = db.Column(db.Integer, primary_key=True)
    access_code_hash = db.Column(db.String(128), unique=True, nullable=False, index=True)
    nom = db.Column(db.String(50), nullable=False)
    prenom = db.Column(db.String(50))
    sexe = db.Column(db.String(20))
    date_naissance = db.Column(db.Date)
    age = db.Column(db.Integer)
    nationalite = db.Column(db.String(50))
    pays = db.Column(db.String(50))
    situation = db.Column(db.String(50))
    langues = db.Column(db.String(100))
    personnes_a_charge = db.Column(db.Integer, default=0)
    telephone = db.Column(db.String(20))
    email = db.Column(db.String(100))
    adresse = db.Column(db.Text)
    quartier = db.Column(db.String(50))
    zone = db.Column(db.String(20))
    statut_logement = db.Column(db.String(30))
    type_logement = db.Column(db.String(30))
    nb_pieces = db.Column(db.Integer)
    acces_eau = db.Column(db.String(10))
    acces_electricite = db.Column(db.String(10))
    niveau_etude = db.Column(db.String(50))
    statut_pro = db.Column(db.String(30))
    profession = db.Column(db.String(100))
    type_contrat = db.Column(db.String(50))
    revenus_usd = db.Column(db.Float)
    etat_sante = db.Column(db.String(20))
    couverture_sante = db.Column(db.String(30))
    handicap = db.Column(db.Boolean, default=False)
    acces_internet = db.Column(db.String(10))
    appareil = db.Column(db.String(50))
    temps_trajet_min = db.Column(db.Integer)
    problemes = db.Column(db.Text)
    besoins = db.Column(db.Text)
    suggestions = db.Column(db.Text)
    satisfaction_globale = db.Column(db.Integer)
    created_at = db.Column(db.DateTime, default=datetime.utcnow)
    consent_rgpd = db.Column(db.Boolean, default=False)

class AuditLog(db.Model):
    __tablename__ = 'audit_log'
    id = db.Column(db.Integer, primary_key=True)
    action = db.Column(db.String(50), nullable=False)
    code_masked = db.Column(db.String(20), nullable=True)
    ip_address = db.Column(db.String(45), nullable=True)
    timestamp = db.Column(db.DateTime, default=datetime.utcnow)
